### ISSUE TITLE
Alexa hookup

### ISSUE THREAD

**Issue by NareshDealer** [darkosancanin/bravia_console#1]
Hi,
I like your simple your code.
I m new to python and also to Alexa skill.. so i m using a simple Lib Flask-Ask to write a skill.
So as i mentioned i m not yet good at python, i would like to pass arguments from alexa script to your script.
For example if i receive a command to TV ON on alexa script.. i might have to pass the same to your script.

It also looks like the pairing with TV is like one in 10 shots. Once i get connected straight and sometimes it cant find the TV.? I m not sure, if i m missing anything but i m trying to do exactly like what i did when it connected successfully.

I really appreciate if you can help me on achieving this.

Thanks.

**Comment by darkosancanin** [comment]
@NareshDealer: I have updated the script to allow you to pass in the IP address of the TV and a command as arguments. e.g. `python bravia_console.py -i 192.168.0.50 -c tvpower`. 

Passing the arguments will skip the search for the TV and send the command and then exit. Hopefully this should allow you to achieve what you are after. Good luck!
